name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Inject Secret Hashes
        run: |
          sed -i "s|TARGET_USER_HASH_PLACEHOLDER|${{ secrets.VAULT_USER_HASH }}|g" index.html
          sed -i "s|TARGET_PASS_HASH_PLACEHOLDER|${{ secrets.VAULT_PASS_HASH }}|g" index.html

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
