name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683

      - name: Inject Secret Hashes
        run: |
          sed -i "s|TARGET_USER_HASH_PLACEHOLDER|${{ secrets.VAULT_USER_HASH }}|g" index.html
          sed -i "s|TARGET_PASS_HASH_PLACEHOLDER|${{ secrets.VAULT_PASS_HASH }}|g" index.html

      - name: Setup Pages
        uses: actions/configure-pages@983d7736b9b0ae728bade1ab49925350fe3abd35

      - name: Upload artifact
        uses: actions/upload-pages-artifact@56166037f1af3be06124491040f7a316b277d353

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@d6db90c60ac5ea60f205c462bb63212f7a935403
